---
title: "output tables"
author: "Kwiz Research Services"
date: '2022-05-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tibble)
library(dplyr)
```

# Populations

## Table 1
```{r}
dirpath <- paste0(getwd(), "/")
pop_df <- readPop(simulate, dirpath) |> tibble() 

df1 <- pop_df |> 
  select(Year, Rep, NInd) |> 
  rename(Species = Rep, Fre.x = NInd) |> # Replicates represents Species, NInds is the frequency of a species x each year
  group_by(Year, Species, .groups = "keep") |> 
  summarise(Fre.x = sum(Fre.x)) |> # sum Fre.x across all locations
  ungroup(Year) |>
  mutate(Cum = cumsum(Fre.x)) |> # cumulative number of the species
  ungroup(Species) |> 
  select(-.groups) |>
  group_by(Year) |>
  mutate(Fre.y = sum(Cum)) # cumulative number of all species

df1 <- df1[order(df1$Species), ] 
table(df1$Species) |> as.data.frame() |> rename(Species = Var1, Years = Freq)
table(df1$Species)
```


## Table 2

```{r}
df2 <- df1 |> select(Year, Fre.y) |> rename(No_specimen = Fre.y)
df2
```